export interface User {
  id?: number;                // optional, generated by backend
  username: string;
  password: string;
  email?: string;             // optional in login, required in signup
  name?: string;              // optional in signup, editable in profile
  description?: string;       // optional in signup, editable in profile
  profilePictureUrl?: string; // optional, handled via profile upload
}